### ISSUE TITLE
Data encrypted in Haskell failing to decrypt in Swift

### ISSUE THREAD

**Issue by tomtitchener** [RNCryptor/rncryptor-hs#11] opened 2016-08-12 18:37 UTC
On the same machine, checked password and data inputs for two compilers match byte-for-byte in haskell and swift apps, but decrypt via swift always fails with error code 1.  Decrypt for Haskell succeeds.

Encrypt (with oodles of trace statements):

encryptText :: RNCryptorContext -> T.Text -> T.Text
encryptText ctx txt = 
  let
    utf8EncodedIn    = traceShowId $ encodeUtf8 txt
    rawBinary        = BS.pack $ traceShowId $ BS.unpack $ encrypt ctx utf8EncodedIn
    base64Encoded    = B64.encode rawBinary
    base64EncodedTxt = traceShowId $ decodeUtf8 base64Encoded
  in
    base64EncodedTxt

Swift code (also with tons of tracing):

let base64String:String = "AwFXR3zRufGnn+emKlb5h/GDSLOuQjeBCXtXhI44/tFpVVAM11Ddm+niLiqWpyIRTZxKS1jv8MQoINVDPN+9OF57RV33ofTPFTPnWljGbW+uzA=="

let decodedData:NSData = NSData(base64EncodedString: base64String, options:NSDataBase64DecodingOptions(rawValue: 0))!

let count = decodedData.length / sizeof(UInt8)

// create an array of Uint8
var array = [UInt8](count: count, repeatedValue: 0)

// copy bytes into array
decodedData.getBytes(&array, length:count * sizeof(UInt8))

print(array)

let password = "password"

let pwdData = password.dataUsingEncoding(NSUTF8StringEncoding)

let pwdCount = pwdData!.length / sizeof(UInt8)

// create an array of Uint8
var pwdArray = [UInt8](count: pwdCount, repeatedValue: 0)

// copy bytes into array
pwdData!.getBytes(&pwdArray, length:pwdCount * sizeof(UInt8))

print(pwdArray)

// Decryption
do {
    let originalData = try RNCryptor.decryptData(decodedData, password: password)
    let originalString = String(data: originalData, encoding: NSUTF8StringEncoding)
    print(originalString)
    // ...
}
catch let error as NSError{
    print(error.localizedDescription)
    
}

Data:

password:  [112,97,115,115,119,111,114,100]

encrypted bytes: [3,1,87,71,124,209,185,241,167,159,231,166,42,86,249,135,241,131,72,179,174,66,55,129,9,123,87,132,142,56,254,209,105,85,80,12,215,80,221,155,233,226,46,42,150,167,34,17,77,156,74,75,88,239,240,196,40,32,213,67,60,223,189,56,94,123,69,93,247,161,244,207,21,51,231,90,88,198,109,111,174,204]

(base64 decode of string:
"AwFXR3zRufGnn+emKlb5h/GDSLOuQjeBCXtXhI44/tFpVVAM11Ddm+niLiqWpyIRTZxKS1jv8MQoINVDPN+9OF57RV33ofTPFTPnWljGbW+uzA==")

**Comment by tomtitchener** [comment] 2016-08-12 18:40
Fix cut'n'paste error updating older base64 data

**Comment by tomtitchener** [comment] 2016-08-12 18:40
Closed by accident!

**Comment by adinapoli** [comment] 2016-08-12 18:46
Hey @tomtitchener , without even looking at your code, I might guess what's going on: we support version 3 of the format, but RNCryptor (the objC and Swift versions) are at version 4. 

Short story short, your best bets are:

1. Downgrade the iOS version
2. Send a patch to implement V4 in this library

What do you think? Is 1. an option for you?

**Comment by rnapier** [comment] 2016-08-13 00:17
The swift and ObjC implementations write the V3 format. Nothing writes a V4 format yet. The "4" you're looking at is the library version, not the data format version

**Comment by adinapoli** [comment] 2016-08-13 05:17
Hey @rnapier, thanks for clarifying! I'm clueless then on why this is happening! I'm using this library in production with a very specific version of the ios implementation, and I never had problems. I'm on holidays these days, but will try to take a look in 2 weeks. In the meantime, if we are able to create minimal reproduction steps, that would help a lot!

**Comment by tomtitchener** [comment] 2016-08-15 12:38
FWIW, looks like it's jut the HMAC computation.  
If I make this change to finalData (essentially gutting it)...
    func finalData() throws -> NSData {
        let result = engine.finalData()
        //let hash = hmac.finalData()
        //if !isEqualInConsistentTime(trusted: hash, untrusted: buffer.finalData()) {
        //    throw RNCryptorError.HMACMismatch
        //}
        return result
    }
... and visually inspect the answer in result, then I see the correct value (decrypted cleartext via Swift equals cleartext pre-encryption on Haskell).

**Comment by tomtitchener** [comment] 2016-08-15 12:42
Note, I'm encrypting short bits of data (< 256 bytes at a time), so I use "encrypt", not "encryptStream".

**Comment by tomtitchener** [comment] 2016-08-15 13:30
Reproduced with encryptStream, FWIW, unfortunately.

**Comment by tomtitchener** [comment] 2016-08-15 13:41
@adinapoli, @rnapier 

Steps to repro:

1.  Use rncryptor-encrypt from repo and base64 to create cypher text with password "password":

```
bash-3.2$ echo 01 | rncryptor-encrypt password | base64 --wrap=0 
AwGxi0OpKIsfQTGJlf/gDue4roeZ95nQkipWFskAoY4O1HbWvxiNUD/y7zhqj/+xHIiNSxl8ChOXW1Nasqp6V+9V6DGq7QuA24M4w+drupOeiA==

```

2. Use XCode to create trivial console app, with base64 encoded string just copied right into code:

```
import Foundation

let password = "password"

let pwdData = password.dataUsingEncoding(NSUTF8StringEncoding)

let base64String:String = "AwGxi0OpKIsfQTGJlf/gDue4roeZ95nQkipWFskAoY4O1HbWvxiNUD/y7zhqj/+xHIiNSxl8ChOXW1Nasqp6V+9V6DGq7QuA24M4w+drupOeiA=="

let decodedData:NSData = NSData(base64EncodedString: base64String, options:NSDataBase64DecodingOptions(rawValue: 0))!

// Decryption
do {
    let originalData = try RNCryptor.decryptData(decodedData, password: password)
    let originalString = String(data: originalData, encoding: NSUTF8StringEncoding)
    print(originalString)
    // ...
}
catch let error as NSError{
    print(error.localizedDescription)

```    
3. Build and run, program fails:

```
The operation couldn’t be completed. (TestDecrypt.RNCryptorError error 1.)
Program ended with exit code: 0

```
4. Gut finalData in DecryptorEngineV3:

```
    func finalData() throws -> NSData {
        let result = engine.finalData()
        //let hash = hmac.finalData()
        //if !isEqualInConsistentTime(trusted: hash, untrusted: buffer.finalData()) {
        //    throw RNCryptorError.HMACMismatch
        //}
        return result
    }

```
5. Build and run, program succeeds:

```
Optional("01\n")
Program ended with exit code: 0
```

**Comment by rnapier** [comment] 2016-08-15 14:18
Thanks. I'm also absolutely packed until Sep 12, but I'm eager to dig into this if @adinapoli doesn't address it first. I definitely want this implementation to run through the validation test suite. You're likely correct that the problem here is incorrect HMAC calculation. Looking at the code it looks like it's only computing the HMAC over the header, not over the header and all of the cipher text. Am I misunderstanding this line from `encrypt` (I believe `clearText` here is actually the cipher text)?

      in renderRNCryptorHeader hdr <> clearText <> (rncHMAC hdr $ mempty)

**Comment by tomtitchener** [comment] 2016-08-15 14:31
@rnapier Excellent catch.  What's actually happening here ...

`(runHMAC hdr $ mempty)`

is calling up a function `ByteString -> ByteString` stored in `RNCryptorHeader` that ... computes the HMAC over the empty `ByteString` ... ugh.

**Comment by tomtitchener** [comment] 2016-08-15 14:34
I'll see if I can come up with some Haskell that plays better with the real standard.

I don't see how anything currently encrypted by the RNcryptor Haskell implementation could be decrypted by anything else --- that didn't play the "hide the HMAC validation step" trick like I hacked into the Swift code.

But there's always the possibility I'm just missing something!

**Comment by tomtitchener** [comment] 2016-08-15 16:05
@rnapier Ugh, unfortunately the easy thing doesn't seem to have done the trick, see below.
Maybe @adinapoli has some pointers about what could be going wrong here ..

```
encrypt :: RNCryptorContext -> ByteString -> ByteString
encrypt ctx input =
  let hdr = ctxHeader ctx
      inSz = B.length input
      (_, clearText) = encryptBlock ctx (input <> pkcs7Padding blockSize inSz)
      renderedRNCryptorHeader = renderRNCryptorHeader hdr
  in renderedRNCryptorHeader <> clearText <> (rncHMAC hdr $ renderedRNCryptorHeader <> clearText)

```

**Comment by adinapoli** [comment] 2016-08-15 16:17
Hey folks,

I'm currently out of town and away from the computer, so it's unlikely I
will look into this any sooner of the 22nd, so Rob, if you have time to
spare, definitely go for it!

I wouldn't be surprised if the problem is with the HMAC validation: the
original implementation was coded in anger to support a use case at work,
and due to the fact we need to decrypt large files (>1GB) and that
streaming hmac validation is quite tricky, that explains the rough edges
around the implementation, sorry! ;)

Alfredo

**Comment by tomtitchener** [comment] 2016-08-15 16:55
@rnapier This bit looks suspicious:

`rncHMAC = const $ sha1PBKDF2 userKey hmacSalt 10000 32`

The type of `const` is `a -> b -> a`, so what happens here is you get a function that takes a single argument, which it ignores, answering instead what it got in its first argument.  

From a quick bit of poking around the RNcryptor spec, I think what's happening at a call like the one below is that the function that's answered by `rncHMAC hdr` just ignores whatever it gets handed (below, the concatenation of the header and cipher text), and answers only HMAC key instead.

`msgHMAC = rncHMAC hdr $ msgHdr <> cipherText`

So we're not even generating an HMAC at all, although we have all the components.

I'll poke around some more to see if I can find the HMAC API in the existing code and just plug it in.

**Comment by tomtitchener** [comment] 2016-08-15 18:20
Yay, got Swift decrypt of Haskell encrypt API (NB not encryptStream) to work.

I'll submit a PR.

**Comment by tomtitchener** [comment] 2016-08-15 18:50
@adinapoli I don't seem to have perms to create a branch so I can create a PR, please.

**Comment by rnapier** [comment] 2016-08-15 19:06
@tomtitchener The way you PR on a opensource repo is to fork it and branch on your fork. Then GitHub will let you create a PR back to the source repo.

**Comment by tomtitchener** [comment] 2016-08-15 20:06
@rnapier D'oh.  Thanks for helping the newbie!  PR submitted.  With caveats.  Many.

**Comment by tomtitchener** [comment] 2016-08-18 20:51
@rnapier A little more help with GitHub, please.  I have updates to my repo for computing and verifying HMACs for block and streaming APIs.   The changes were pretty extensive, as I had to convert to the cryptonite package for incremental hmac APIs.  So I created a new branch on the repo I forked.  But now when I try to push up to GitHub I get an error message saying "git push --set-upstream origin generate-encrypt-hmac".  But when I try that I get access denied/403.

**Comment by rnapier** [comment] 2016-08-18 21:26
@tomtitchener You may be pushing to the wrong remote. Use `git remote -v` to make sure that `origin` is your branch and not the official repo. You may already have a remote setup for your fork (can't remember if you get that automatically); if so you can push to that (replace "origin" with your remote).

See [Managing Remotes](https://help.github.com/categories/managing-remotes/) for more about that. I usually keep two remotes around, one for the origin and one for my fork; makes it easier to merge upstream changes. See [Adding a remote](https://help.github.com/articles/adding-a-remote/) for how to do that.

**Comment by tomtitchener** [comment] 2016-08-19 14:37
@rnapier, PR updated with changes for streaming encrypt and decrypt.  I'll put the test vector integration on my to-do list.  Thanks for your very helpful help!

**Comment by tomtitchener** [comment] 2016-08-19 19:40
@adinapoli Fixes submitted to this PR.  TBD:  streaming tests, version bump, adding me as a contributor.

**Comment by adinapoli** [comment] 2016-08-19 19:41
Thanks Tom!

Will try to finalise everything this weekend!

Alfredo

**Comment by adinapoli** [comment] 2016-08-23 19:49
Tentatively fixed by https://github.com/RNCryptor/rncryptor-hs/pull/13

**Closed by adinapoli** 2016-08-23 19:49 UTC
